### ISSUE TITLE
Add CC0 license to design files

### ISSUE THREAD

**Issue by abetusk** [joshmaceachern/OSMMPump#2]
From a comment on [Reddit](https://www.reddit.com/r/functionalprint/comments/hsevpl/opensource_multichannel_microfluidicsosmm_pump/fy9z8qz/) (that I assume is the author of this project), the intent is for the design files to be under a CC0/Public Domain license.

A CC0 license should be added to the appropriate sub-directories as well as be mentioned in the README so that others know what license the Step and STL files are under.

Thanks for making this awesome project available to the community!

**Comment by joshmaceachern** [comment]
Thanks for letting me know!
